### PR TITLE
Add support for GCE labels

### LINKED ISSUE #58: Add Support For Setting Labels On Launched Instances
kitchen-google currently supports setting GCE metadata on launched instances. It would be nice if kitchen-google could also set labels on launched instances. See below link for a high level overview on GCE labels.

https://cloud.google.com/compute/docs/labeling-resources

### PR DESCRIPTION
**Pull request by seanmalloy**
Instances can now be launched with a list
of GCE labels. Labels are specified as a hash.

Close #58

### CODE REVIEW

**Comment by seanmalloy** [comment]
I know that I still need to write the unit tests for these code changes. I'm hoping to push up the unit tests for these code changes soon.

Please provide feedback on the code changes that I've pushed so far.

**Comment by seanmalloy** [comment]
@robbkidd and @adamleff would it be possible to get a review on this?

**Comment by adamleff** [comment]
@jjasghar is this something you can help with?

**Comment by seanmalloy** [comment]
@adamleff and @jjasghar friendly reminder that this PR still needs a review.

**Comment by seanmalloy** [comment]
@adamleff and @jjasghar any feedback on the PR?

**Comment by jjasghar** [comment]
I’ll revisit it ASAP. Sorry about the delay.

**Comment by seanmalloy** [comment]
@jjasghar no worries. Just wanted to make sure I don't forget about this PR. Let me know if any code changes are required.

**Comment by seanmalloy** [comment]
@jjasghar would it be possible to get a review on this PR?

**Comment by seanmalloy** [comment]
Would it be possible to get some feedback on this pull request?

**Pull request merged**
