### PR TITLE
add support for defining custom inst_name

### PR DESCRIPTION
**Pull request by twmb**

### CODE REVIEW

**Comment by mattse** [comment]
I would also like a variation of this feature.

If you supply a single instance name, then what happens when you have multiple suites running at once, there will be a name conflict and GCE will refuse to allow you to use that instance name.

What I would like is an `instance_name_prefix` that would replace the `tk` prefix that is currently used.

**Comment by fabianmet** [comment]
I would prefer being able to set the entire instance name, without any auto generation.

This is because in my use case we build multiple suites that need to communicate together. Where we define the instance name per suite.

This so that we can get some easy networking going between instances. For instance in use with certain clusters.

**Comment by pietervogelaar** [comment]
+1

**Comment by robbkidd** [comment]
Closing this PR in favor of #54, a slightly simpler implementation of the same behavior. My apologies for the hang time on this change.

**Pull request closed without merging**
