### PR TITLE
Inject ssh key for test-kitchen-user using Google Cloud metadata

### PR DESCRIPTION
**Pull request by zbikmarc**
This PR lets test-kitchen to inject public key from provided file (path) and allow `env_user` to connect to virtual machine using this public key.

I have no idea how to write proper tests for this.

### CODE REVIEW

**Comment by zbikmarc** [comment]
Strange build error:
```
Running RuboCop...

Inspecting 7 files

...C...

Offenses:

lib/kitchen/driver/gce.rb:533:9: C: Style/RedundantBegin: Redundant begin block detected.

        begin

        ^^^^^

7 files inspected, 1 offense detected

RuboCop failed!
```
My change did not touch this line at all.

**Comment by zbikmarc** [comment]
Tests are now failing due to ruby 2.0 and 2.1
```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby
    chefstyle was resolved to 0.6.0, which depends on
      ruby (>= 2.2)
    kitchen-google was resolved to 1.2.0, which depends on
      ruby (>= 2.0)
The command "eval bundle install --jobs=3 --retry=3 " failed. Retrying, 2 of 3.
```
@anl Can you look at this?

**Comment by zbikmarc** [comment]
Thank you @robbkidd

**Comment by ErikThoreson** [comment]
i'd like to see this added as well.

**Comment by robbkidd** [comment]
@zbikmarc Testing is admittedly tricky. That's something I can help with.

Can you add some documentation to the README about this new [config option](https://github.com/test-kitchen/kitchen-google#configuration), how to use it, and what a user should expect when they do? For example, this pub key declared in the `driver` section must match the `ssh_key` declared under `transport`.

**Comment by robbkidd** [comment]
@zbikmarc Thank you for this change and the impetus to get this behavior supported in the plugin. This week's testing showed that the implementation of generic custom metadata in #43 (1) conflicts with these changes and (2) also provides a mechanism to set the `ssh_keys` metadata.

We've merged #43 for a more general solution. I propose that we close this PR in favor of an update to the README that provides an example of setting `ssh_keys` through the new custom metadata keys and how to read in username and public key content to the kitchen.yml with either environment variables or ERb.

**Comment by zbikmarc** [comment]
@robbkidd I am ok with this. Just will need to find out a simple way to do this.

**Comment by robbkidd** [comment]
> Just will need to find out a simple way to do this.

**Comment by robbkidd** [comment]
How's this?

```
driver:
  name: gce
  metadata:
    ssh-keys: <%= ENV['USER'] + ':' + IO.binread("#{ENV['SSH_KEY']}.pub").rstrip! %>

transport:
  username: <%= ENV['USER'] %>
  ssh_key: <%= ENV['SSH_KEY'] %>
```

Set the environment variable `SSH_KEY` to the path for the private key and the embedded Ruby will use it for the transport private key and for the public key to add to metadata.

**Comment by zbikmarc** [comment]
I think this should do the job.
I will confirm this.

**Pull request closed without merging**
